// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

function resolve_action(str) {
  switch (str) {
    case "(" : 
        return /* UP */1;
    case ")" : 
        return /* DOWN */2;
    default:
      return /* NONE */0;
  }
}

function calculate_floor(data, _floor, _index) {
  while(true) {
    var index = _index;
    var floor = _floor;
    var len = data.length;
    if (index < len) {
      var action = resolve_action($$String.make(1, Caml_string.get(data, index)));
      var next_floor;
      switch (action) {
        case 0 : 
            next_floor = floor;
            break;
        case 1 : 
            next_floor = floor + 1 | 0;
            break;
        case 2 : 
            next_floor = floor - 1 | 0;
            break;
        
      }
      var next_index = index + 1 | 0;
      _index = next_index;
      _floor = next_floor;
      continue ;
    } else {
      return floor;
    }
  };
}

function exec($staropt$star, data) {
  var initial_floor = $staropt$star !== undefined ? $staropt$star : 0;
  return calculate_floor(data, initial_floor, 0);
}

function solve(data) {
  return (function (param) {
      return exec(param, data);
    });
}

exports.resolve_action = resolve_action;
exports.calculate_floor = calculate_floor;
exports.exec = exec;
exports.solve = solve;
/* No side effect */
