// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function calculate_wrapping_paper(_, _$1) {
  return 0;
}

function solve(input) {
  return Promise.resolve(calculate_wrapping_paper(input, 0));
}

exports.calculate_wrapping_paper = calculate_wrapping_paper;
exports.solve = solve;
/* No side effect */
