// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var AOC2015_1 = require("./AOC2015_1.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function main() {
  Pervasives.print_string("************************");
  Pervasives.print_string("Advent of Code solutions");
  Pervasives.print_string("************************");
  return AOC2015_1.solve("()())()");
}

main(/* () */0);

exports.main = main;
/*  Not a pure module */
